overrides:
  lodash-es: 4.18.1
  markdown-it: ">=14.2.0"
  rollup: ">=4.59.0"
  postcss: 8.5.23
  browserslist: 4.28.7
  postcss-selector-parser: 6.1.3
  ws: 8.21.0
  linkify-it: 5.0.2
  "@tiptap/extension-bubble-menu": 3.31.3
  "@tiptap/extension-floating-menu": 3.31.3
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67
  vite-plus: 0.0.0-commit.40ce1b34104d16f3c3a2d9fe8eb1b016f5a06b67
