using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Ivy.Test")]
[assembly: InternalsVisibleTo("Ivy.Tests")]
[assembly: InternalsVisibleTo("Ivy.Docs")]
[assembly: InternalsVisibleTo("Ivy.Desktop")]
[assembly: InternalsVisibleTo("Ivy.Integration.Tests")]
[assembly: InternalsVisibleTo("Ivy.XamlBuilder")]
[assembly: InternalsVisibleTo("Ivy.XamlBuilder.Test")]
[assembly: InternalsVisibleTo("Ivy.Tendril")]
[assembly: InternalsVisibleTo("Ivy.Agent.Test.Studio")]
[assembly: InternalsVisibleTo("Ivy.IvyML")]
[assembly: InternalsVisibleTo("Ivy.Hooks.Pty.Test")]
[assembly: InternalsVisibleTo("Ivy.Agent.Filter.Tests")]
// [assembly: InternalsVisibleTo("Ivy.Docs.Shared")]
// [assembly: InternalsVisibleTo("Ivy.Samples.Shared")]